---
- name: Create Namespaces
  hosts: controller
  become: yes
  vars:
    sportsify_namespace: "sportsify-ns"
    jenkins_namespace: "jenkins"

  tasks:

    - name: Create Jenkins namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ jenkins_namespace }}"
        state: present

    - name: Create Sportsify namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ sportsify_namespace }}"
        state: present